name: Run Migrations

on:
  push:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      # Clone the repository to $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # Cache deps for a faster install
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      # Install
      - run: npm ci

      # Check it passes lint
      - run: npm run lint

      # Compile typescript
      - run: npm run build

      # Run the migration
      - run: npm start
        env:
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
